=== xs-han/JavaClass/TeacherShare/JAVA_class_1_2017_04_08/XML_FamilyUser/FamilyUser.dtd
<?xml version="1.0" encoding="UTF-8" ?>
<!ELEMENT FamilyUser (row+)>
<!ELEMENT row (u_id,u_name,u_pwd,u_memo)>
<!ELEMENT u_id (#PCDATA)>
<!ELEMENT u_name (#PCDATA)>
<!ELEMENT u_pwd (#PCDATA)>
<!ELEMENT u_memo (#PCDATA)>

=== xs-han/JavaClass/TeacherShare/JAVA_class_1_2017_04_08/XML_FamilyUser/FamilyUser.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE FamilyUser SYSTEM "FamilyUser.dtd">
<?xml-stylesheet type="text/xsl" href="FamilyUser.xsl"  ?>
<FamilyUser>
  <row>
    <u_id>01</u_id>
    <u_name>admin</u_name>
    <u_pwd>123456</u_pwd>
    <u_memo>13242398473</u_memo>
  </row>
  <row>
    <u_id>02</u_id>
    <u_name>peter</u_name>
    <u_pwd>654321</u_pwd>
    <u_memo>13842398473</u_memo>
  </row>
  <row>
    <u_id>03</u_id>
    <u_name>Allen</u_name>
    <u_pwd>123456</u_pwd>
    <u_memo>13242398473</u_memo>
  </row>
  <row>
    <u_id>04</u_id>
    <u_name>mary</u_name>
    <u_pwd>654321</u_pwd>
    <u_memo>13842398473</u_memo>
  </row>
</FamilyUser>
