=== xs-han/JavaClass/TeacherShare/JAVA_class_1_2017_04_08/XML_LX/student0.dtd
<?xml version="1.0"  encoding="UTF-8"?>
<!ELEMENT student (row+)>
<!ELEMENT row (sid,sname,sage,smobile,semail,saddress)>
<!ELEMENT sid (#PCDATA)>
<!ELEMENT sname (#PCDATA)>
<!ELEMENT sage (#PCDATA)>
<!ELEMENT smobile (#PCDATA)>
<!ELEMENT semail (#PCDATA)>
<!ELEMENT saddress (#PCDATA)>

=== xs-han/JavaClass/TeacherShare/JAVA_class_1_2017_04_08/XML_LX/student0.xml
<?xml version="1.0" encoding="GB2312" standalone="no"?>
<!DOCTYPE student SYSTEM "student0.dtd">
<?xml-stylesheet type="text/xsl" href="student0.xsl"?>
<student>
  <row>
    <sid>s01</sid>
    <sname>李小龙</sname>
    <sage>32</sage>
    <smobile>13423483473</smobile>
    <semail>lql@126.com</semail>
    <saddress>Queen avenue.</saddress>
  </row>
  <row>
    <sid>s02</sid>
    <sname>张三丰</sname>
    <sage>18</sage>
    <smobile>13423483473</smobile>
    <semail>lql@126.com</semail>
    <saddress>Queen avenue.</saddress>
  </row>
  <row>
    <sid>s03</sid>
    <sname>张丰</sname>
    <sage>18</sage>
    <smobile>13423483473</smobile>
    <semail>lql@126.com</semail>
    <saddress>Queen avenue.</saddress>
  </row>
  <row>
    <sid>s04</sid>
    <sname>张三</sname>
    <sage>28</sage>
    <smobile>13423483473</smobile>
    <semail>lql@126.com</semail>
    <saddress>Queen avenue.</saddress>
  </row>
  <row>
    <sid>s05</sid>
    <sname>三丰</sname>
    <sage>18</sage>
    <smobile>13423483473</smobile>
    <semail>lql@126.com</semail>
    <saddress>Queen avenue.</saddress>
  </row>
  <row>
    <sid>s01</sid>
    <sname>李小龙</sname>
    <sage>32</sage>
    <smobile>13423483473</smobile>
    <semail>lql@126.com</semail>
    <saddress>Queen avenue.</saddress>
  </row>
  <row>
    <sid>s02</sid>
    <sname>张三丰</sname>
    <sage>18</sage>
    <smobile>13423483473</smobile>
    <semail>lql@126.com</semail>
    <saddress>Queen avenue.</saddress>
  </row>
  <row>
    <sid>s03</sid>
    <sname>张丰</sname>
    <sage>18</sage>
    <smobile>13423483473</smobile>
    <semail>lql@126.com</semail>
    <saddress>Queen avenue.</saddress>
  </row>
  <row>
    <sid>s04</sid>
    <sname>张三</sname>
    <sage>28</sage>
    <smobile>13423483473</smobile>
    <semail>lql@126.com</semail>
    <saddress>Queen avenue.</saddress>
  </row>
  <row>
    <sid>s05</sid>
    <sname>三丰</sname>
    <sage>18</sage>
    <smobile>13423483473</smobile>
    <semail>lql@126.com</semail>
    <saddress>Queen avenue.</saddress>
  </row>
</student>
